apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  name: anthosday-appmod-onair-20210623-demo
spec:
  storageClass: REGIONAL
  location: asia-northeast1
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7