apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: sqldatabase-sample
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: sqldatabase-dep
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: sqldatabase-dep
spec:
  region: asia-northeast1
  databaseVersion: MYSQL_8_0
  settings:
    tier: db-n1-standard-1